version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: batch
      MYSQL_USER: junseok
      MYSQL_PASSWORD: 1234
    ports:
      - "53306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_project_network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_project_network

networks:
  app_project_network:
    name: app_project_network
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data
  redis_data:
    name: redis_data